### ISSUE TITLE
Wheatley does not react to portals being placed behind him

### ISSUE THREAD

**Issue by vrad-exe** [EpicSentry/P2ASW#6]
In Portal 2, Wheatley's lines in `sp_a1_intro7` will change after you place a portal behind him, to no longer mention that you need to place a portal. This doesn't work in p2asw.

https://github.com/EpicSentry/P2ASW/assets/19228201/458b843c-2823-4df9-9215-2235c342d5bf

Regular Portal 2, for comparison:

https://github.com/EpicSentry/P2ASW/assets/19228201/71289ebd-2cff-4630-926c-484a1fdc7000

**Comment by Jordon87** [comment]
func_portal_detector would need to be updated more in order for this to work properly.

**Comment by Jordon87** [comment]
Late reply but the problem's been fixed now, Wheatley will no longer nag about the portal.
